[tool.poetry]
name = "tensorpack"
version = "0.0.2"
description = "A collection of tensor methods from the Meyer lab."
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.21"
scipy = "^1.7"
statsmodels = "^0.13"
tensorly = "^0.7"
scikit-learn = "^1.0.1"
matplotlib = "^3.5.0"
seaborn = "^0.11.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
statsmodels = "^0.13"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
